# Generated by Django 5.1.3 on 2024-12-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
