# Generated by Django 5.1.3 on 2024-12-25 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0002_creditrating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditRating",
        ),
    ]
