# Generated by Django 5.1.3 on 2024-12-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0003_delete_creditrating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_rating",
            field=models.CharField(
                choices=[
                    ("1", "Level 1"),
                    ("2", "Level 2"),
                    ("3", "Level 3"),
                    ("4", "Level 4"),
                    ("5", "Level 5"),
                ],
                max_length=1,
            ),
        ),
    ]
