# Generated by Django 5.1.3 on 2024-12-25 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookstore", "0004_alter_customer_credit_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutOfStockBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_title", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=0)),
                ("registration_date", models.DateField(auto_now_add=True)),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookstore.publisher",
                    ),
                ),
            ],
        ),
    ]
